title: Hossein Karagah
logo: /assets/img/headshot.png
# description: text below image
# show_downloads: true
theme: jekyll-theme-minimal # for other options go to: https://pages.github.com/themes/
include:
  - structure
baseurl: "/portfolio"
url: "https://hosseinkaragah.github.io"
navigation:
  - title: Home
    url: /
  - title: Structural Engineering
    url: /structure/
